import { useMemo, useState, useRef, useEffect } from "react";
import { ArrowUpRight, ArrowRight, ArrowLeft, Check, ChevronRight, Download, FlaskConical, GitCompareArrows, Hexagon, Layers, MapPin, Search, Settings2, Sparkles, Upload, X, RotateCcw, Route, Pentagon, Plus, SlidersHorizontal, Info, FileText, Trash2 } from "lucide-react";
import { ResponsiveContainer, RadarChart, Radar, PolarGrid, PolarAngleAxis, PolarRadiusAxis } from "recharts";
import type { FeatureCollection, Geometry } from "geojson";
import { listCities, buildCityData } from "@/lib/sitescope/mock-data";
import { scoreCity, topSites, FACTORS, distanceKm } from "@/lib/sitescope/scoring";
import { useSiteScope } from "@/lib/sitescope/store";
import { CONSTRAINT_LABELS } from "@/lib/sitescope/resolve";
import { applyScenario, EMPTY_SCENARIO, clusters, travelBands, insidePolygon, interpretBrief, businessConfig, type Point, type Scenario } from "@/lib/sitescope/analysis";
import { ExplorerMap, type DisplayLayer, type UploadedLayer } from "./ExplorerMap";
import { exportCSV, exportPDF } from "@/lib/export";
import type { LayerId, HexCell } from "@/lib/sitescope/types";

const BUSINESSES=[{id:"ev",label:"EV charging station"},{id:"cafe",label:"Café & bakery"},{id:"retail",label:"Retail store"},{id:"warehouse",label:"Warehouse"},{id:"clinic",label:"Healthcare clinic"},{id:"gym",label:"Fitness studio"},{id:"restaurant",label:"Restaurant"},{id:"grocery",label:"Grocery store"},{id:"pharmacy",label:"Pharmacy"},{id:"salon",label:"Salon"}];
const INITIAL_LAYERS:DisplayLayer[]=[
  {id:"score",label:"Site readiness",color:"#438b70",visible:true,opacity:62},
  {id:"population",label:"Population density",color:"#7d97c9",visible:false,opacity:55},
  {id:"accessibility",label:"Transport accessibility",color:"#489cbd",visible:false,opacity:55},
  {id:"competition",label:"Competitors & density",color:"#d48b70",visible:false,opacity:55},
  {id:"landuse",label:"Land use & zoning",color:"#b29ac9",visible:false,opacity:55},
  {id:"risk",label:"Flood risk",color:"#dc8d92",visible:false,opacity:55},
  {id:"footfall",label:"Pedestrian footfall",color:"#bf9a59",visible:false,opacity:55},
  {id:"complementary",label:"Nearby amenities",color:"#7fa387",visible:false,opacity:55},
  {id:"rent",label:"Affordability",color:"#84afa8",visible:false,opacity:55},
];
const format=(n:number)=>new Intl.NumberFormat("en-IN",{maximumFractionDigits:0}).format(n);
const siteName=(id:string)=>`Site ${id.slice(5,11).toUpperCase()}`;
type Panel="layers"|"weights"|"scenario"|"compare"|"reports"|null;

export function SiteWorkspace({onBack,onReset}:{onBack:()=>void;onReset:()=>void}) {
  const state=useSiteScope();
  const city=state.city??listCities()[0]!;
  const config=state.activeConfig??businessConfig("cafe");
  const business=state.answers['q1']?.optionIds[0]??"cafe";
  const businessLabel=BUSINESSES.find(b=>b.id===business)?.label??"Custom business";
  const [panel,setPanel]=useState<Panel>(null),[detailTab,setDetailTab]=useState("overview");
  const [layers,setLayers]=useState(INITIAL_LAYERS),[overlay,setOverlay]=useState("none");
  const [scenario,setScenario]=useState<Scenario>(EMPTY_SCENARIO),[before,setBefore]=useState(false);
  const [placing,setPlacing]=useState(false),[drawing,setDrawing]=useState(false),[draft,setDraft]=useState<Point[]>([]);
  const [uploaded,setUploaded]=useState<UploadedLayer[]>([]),[overrides,setOverrides]=useState<Record<string,Partial<HexCell>>>({});
  const [brief,setBrief]=useState(""),[notes,setNotes]=useState<string[]>([]),[search,setSearch]=useState("");
  const [notice,setNotice]=useState(""),[showTravel,setShowTravel]=useState(false);
  const [mode,setMode]=useState<"walk"|"drive">(config.isochroneMode);
  const [roadTravel,setRoadTravel]=useState<ReturnType<typeof travelBands>|null>(null),[routing,setRouting]=useState(false);
  const uploadRef=useRef<HTMLInputElement>(null),routingVersion=useRef(0);
  const data=useMemo(()=>{const d=buildCityData(city.id);return {...d,hexes:d.hexes.map(h=>({...h,...overrides[h.h3]}))};},[city.id,overrides]);
  const simulated=useMemo(()=>applyScenario(data,scenario),[data,scenario]);
  const baseline=useMemo(()=>scoreCity(data,config),[data,config]);
  const scored=useMemo(()=>scoreCity(simulated,config),[simulated,config]);
  const filtered=useMemo(()=>state.drawnPolygon?scored.filter(h=>insidePolygon(h.center,state.drawnPolygon!)):scored,[scored,state.drawnPolygon]);
  const top=useMemo(()=>topSites(filtered,5),[filtered]);
  const selected=scored.find(h=>h.h3===state.selectedH3)??top[0]??filtered[0]??null;
  const baseSelected=baseline.find(h=>h.h3===selected?.h3);
  const eligible=filtered.filter(h=>h.eligible);
  const average=eligible.length?eligible.reduce((s,h)=>s+h.score100,0)/eligible.length:0;
  const hasScenario=scenario.growth!==0||scenario.accessLoss!==0||scenario.flood!==0||scenario.competitors.length>0;
  const clusterData=useMemo(()=>clusters(simulated.competitors.map(c=>c.lngLat)),[simulated]);
  const modeledTravel=useMemo(()=>selected&&showTravel?travelBands(simulated,selected.h3,mode):[],[simulated,selected?.h3,showTravel,mode]);
  const bands=showTravel?(roadTravel??modeledTravel):[];
  const candidates=state.compare.map(id=>scored.find(h=>h.h3===id)).filter((h):h is NonNullable<typeof h>=>!!h);
  const baseRanks=useMemo(()=>new Map(topSites(baseline,baseline.length).map((h,i)=>[h.h3,i+1])),[baseline]);
  const newRanks=useMemo(()=>new Map(topSites(scored,scored.length).map((h,i)=>[h.h3,i+1])),[scored]);
  useEffect(()=>{if(!state.selectedH3&&top[0])state.selectHex(top[0].h3);},[state.selectedH3,top]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(""),6000);return()=>clearTimeout(t);},[notice]);
  useEffect(()=>{routingVersion.current++;setRoadTravel(null);setRouting(false);},[city.id,selected?.h3,mode,simulated]);
  useEffect(()=>{const dismiss=(e:KeyboardEvent)=>{if(e.key==="Escape"){setPanel(null);setDrawing(false);setPlacing(false);}};window.addEventListener("keydown",dismiss);return()=>window.removeEventListener("keydown",dismiss);},[]);
  function changeCity(id:string){const c=listCities().find(c=>c.id===id)!;state.setCity(c);state.selectHex(null);state.setDrawnPolygon(null);state.compare.forEach(state.toggleCompare);setScenario(EMPTY_SCENARIO);setUploaded([]);setOverrides({});setShowTravel(false);setDraft([]);setDrawing(false);setPlacing(false);setSearch("");}
  function changeBusiness(id:string){state.setAnswer("q1",{optionIds:[id]});const c=businessConfig(id);state.setResolved(c,[`Applied ${id} profile`],false);setMode(c.isochroneMode);setNotice("Business profile applied. Scores and recommendations updated.");}
  function togglePanel(p:Panel){setPanel(panel===p?null:p);}
  function addCompare(id:string){if(!state.compare.includes(id)&&state.compare.length===3){setNotice("Compare holds three sites. Remove one to add another.");return;}state.toggleCompare(id);}
  function onMapPoint(p:Point){if(drawing)setDraft(d=>[...d,p]);else if(placing){setScenario(s=>({...s,competitors:[...s.competitors,p]}));setPlacing(false);setBefore(false);setNotice("Competitor added. Rankings recalculated.");}}
  function runBrief(){if(!brief.trim())return;const result=interpretBrief(brief,config);state.setActiveConfig(result.config);if(result.business)state.setAnswer("q1",{optionIds:[result.business==="café"?"cafe":result.business]});setMode(result.config.isochroneMode);setNotes(result.notes);}
  function runSearch(){const query=search.trim().toLowerCase();const pair=query.split(/[,\s]+/).map(Number);if(pair.length===2&&pair.every(Number.isFinite)){const p:Point=[pair[1]!,pair[0]!];const nearest=[...scored].sort((a,b)=>distanceKm(a.center,p)-distanceKm(b.center,p))[0];if(nearest&&distanceKm(nearest.center,p)<2){state.selectHex(nearest.h3);setNotice(`Selected nearest analyzed cell, ${Math.round(distanceKm(nearest.center,p)*1000)} m away.`);}else setNotice("These coordinates fall outside the analyzed city grid.");return;}const found=scored.find(h=>h.h3.includes(query)||siteName(h.h3).toLowerCase()===query);if(found&&query)state.selectHex(found.h3);else setNotice("Search by site ID or latitude, longitude, e.g. 23.0225, 72.5714.");}
  async function roadCatchment(){if(!selected)return;const version=++routingVersion.current;setRouting(true);setRoadTravel(null);setShowTravel(true);
    try{
      const times=new Map<string,number>();
      // OSRM driving table, one origin and batches of cell centroids; full analyzed-grid coverage.
      for(let offset=0;offset<simulated.hexes.length;offset+=80){if(version!==routingVersion.current)return;const batch=simulated.hexes.slice(offset,offset+80);
        const coordinates=[selected.center,...batch.map(h=>h.center)].map(p=>p.join(",")).join(";");
        const response=await fetch(`https://router.project-osrm.org/table/v1/driving/${coordinates}?sources=0&annotations=duration`,{signal:AbortSignal.timeout(12000)});
        if(!response.ok)throw new Error("Routing service unavailable");const result=await response.json() as {code:string;durations:(number|null)[][]};
        if(result.code!=="Ok"||!result.durations?.[0])throw new Error("No route data returned");batch.forEach((h,i)=>{const seconds=result.durations[0]![i+1];if(typeof seconds==="number")times.set(h.h3,seconds/60);});
      }
      if(version!==routingVersion.current)return;
      const modeled=travelBands(simulated,selected.h3,"drive");
      const result=modeled.map(b=>{const cells=simulated.hexes.filter(h=>(times.get(h.h3)??Infinity)<=b.minutes);return {...b,cells:cells.map(h=>h.h3),population:Math.round(cells.reduce((s,h)=>s+h.population*4200,0)),area:cells.length*(modeled[2]!.area/(modeled[2]!.cells.length||1))};});
      setRoadTravel(result);setNotice("Road travel times loaded from OSRM. Population remains synthetic.");
    }catch{if(version===routingVersion.current)setNotice("OSRM could not be reached. Showing the labeled demo network estimate.");}
    finally{if(version===routingVersion.current)setRouting(false);}
  }
  async function importLayer(file:File){try{
    if(file.size>5_000_000)throw new Error("Choose a GeoJSON file smaller than 5 MB.");
    const json=JSON.parse(await file.text()) as FeatureCollection;
    if(json.type!=="FeatureCollection"||!Array.isArray(json.features)||!json.features.length||json.features.length>10000)throw new Error("Use a non-empty GeoJSON FeatureCollection with up to 10,000 features.");
    let vertices=0;
    const validateCoordinates=(value:unknown):boolean=>{if(!Array.isArray(value))return false;if(typeof value[0]==="number"){vertices++;return value.length>=2&&Number.isFinite(value[0])&&typeof value[1]==="number"&&Number.isFinite(value[1])&&Math.abs(value[0])<=180&&Math.abs(value[1])<=90;}return value.length>0&&value.every(validateCoordinates);};
    for(const f of json.features){const g=f.geometry as Exclude<Geometry,{type:"GeometryCollection"}>;if(f.type!=="Feature"||!g||!["Point","MultiPoint","LineString","MultiLineString","Polygon","MultiPolygon"].includes(g.type)||!validateCoordinates(g.coordinates)||vertices>100000)throw new Error("Invalid geometry. Use WGS84 coordinates (longitude, latitude).");}
    const next:Record<string,Partial<HexCell>>={};let count=0;
    for(const f of json.features){const p=f.properties??{};const h=data.hexes.find(h=>p['h3']===h.h3||(f.geometry.type==="Polygon"&&insidePolygon(h.center,f.geometry.coordinates[0] as Point[])));
      const ring=f.geometry.type==="Polygon"?f.geometry.coordinates[0] as Point[]:null;
      const matches=ring?data.hexes.filter(h=>insidePolygon(h.center,ring)):h?[h]:[];
      for(const cell of matches){const patch:Partial<HexCell>={};for(const key of ["population","footfall","accessibility","complementary","rent","floodRisk","parking"] as const)if(typeof p[key]==="number"&&Number.isFinite(p[key])&&p[key]>=0&&p[key]<=1)patch[key]=p[key];if(["commercial","mixed","industrial","residential"].includes(p['landuse']))patch.landuse=p['landuse'];if(Object.keys(patch).length){next[cell.h3]={...next[cell.h3],...patch};count++;}}
    }
    setUploaded(l=>[...l,{name:file.name,data:json,visible:true}]);setOverrides(o=>{const merged={...o};for(const [id,patch] of Object.entries(next))merged[id]={...merged[id],...patch};return merged;});setNotice(`Imported ${json.features.length} features. ${count?`${Object.keys(next).length} cells updated in scoring.`:"Overlay added; no matching scoring attributes."}`);
  }catch(e){setNotice(e instanceof Error?e.message:"Could not read this file.");}finally{if(uploadRef.current)uploadRef.current.value="";}}
  const report=()=>exportPDF(city.name,businessLabel,top.slice(0,3),config.weights,average,{scenario,constraints:config.constraints,total:filtered.length,eligible:eligible.length});
  return <div className="scope-app">
    <header className="scope-header">
      <button className="brand" onClick={onReset}><span className="brand-symbol"><Hexagon size={22}/><span/></span>SiteScope<span className="brand-dot">.</span></button>
      <div className="header-divider"/><span className="workspace-name">Location intelligence</span>
      <nav className="workspace-nav"><button className={!panel||["layers","weights"].includes(panel)?"active":""} onClick={()=>setPanel(null)}>Explore</button><button className={panel==="scenario"?"active":""} onClick={()=>setPanel("scenario")}>Simulate <span className="new-tag">NEW</span></button><button className={panel==="compare"?"active":""} onClick={()=>setPanel("compare")}>Compare {state.compare.length>0&&<span className="count-tag">{state.compare.length}</span>}</button></nav>
      <div className="header-right"><span className="demo-tag"><i/>Demo dataset</span><button className="button small" onClick={()=>setPanel("reports")}><Download size={15}/>Export</button><button className="avatar" title="Edit analysis preferences" onClick={onBack}>SS</button></div>
    </header>
    <div className="workspace-heading"><div><div className="eyebrow">YOUR NEXT LOCATION, BACKED BY DATA</div><h1>Find your place to grow<span>.</span></h1><p>Explore the city. Understand the trade-offs. Choose with confidence.</p></div><div className="city-picker"><MapPin size={17}/><select aria-label="Analysis city" value={city.id} onChange={e=>changeCity(e.target.value)}>{listCities().map(c=><option key={c.id} value={c.id}>{c.name}, Gujarat</option>)}</select></div></div>
    <div className="workspace-layout">
      <aside className="analysis-sidebar">
        <div className="sidebar-heading"><span className="section-label">YOUR ANALYSIS</span><button className="icon-button" aria-label="Edit questionnaire" onClick={onBack}><Settings2 size={16}/></button></div>
        <label className="field-label" htmlFor="business">I’m looking to open</label><select className="field business-select" id="business" value={business} onChange={e=>changeBusiness(e.target.value)}>{BUSINESSES.map(b=><option key={b.id} value={b.id}>{b.label}</option>)}</select>
        <div className="brief-box"><div className="brief-title"><Sparkles size={15}/>Describe your ideal location</div><textarea aria-label="Location brief" value={brief} onChange={e=>setBrief(e.target.value)} placeholder="Near highways, low flood risk, away from competitors…"/><div className="brief-bottom"><span>Local brief interpreter</span><button disabled={!brief.trim()} aria-label="Apply location brief" onClick={runBrief}><ArrowRight size={17}/></button></div></div>
        {notes.length>0&&<div className="brief-notes" role="status">{notes.map((n,i)=><p key={i}><Check size={12}/>{n}</p>)}<button onClick={()=>setNotes([])}>Dismiss</button></div>}
        <div className="priority-heading"><span className="section-label">WHAT MATTERS TO YOU</span><button className="text-button" onClick={()=>setPanel("weights")}>Adjust <SlidersHorizontal size={12}/></button></div>
        <div className="weight-preview">{Object.entries(config.weights).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([k,v])=><div key={k}><span>{FACTORS[k]??k}</span><div><i style={{width:`${v/Object.values(config.weights).reduce((s,n)=>s+n,0)*100}%`}}/></div><b>{Math.round(v/Object.values(config.weights).reduce((s,n)=>s+n,0)*100)}%</b></div>)}</div>
        <div className="sidebar-rule"/>
        <div className="recommendation-heading"><div><span className="section-label">BEST-FIT LOCATIONS</span><p>Ranked for your business</p></div><span className="count-tag">{top.length}</span></div>
        <div className="recommendations">{top.map((h,i)=><button key={h.h3} className={`recommendation ${selected?.h3===h.h3?"selected":""}`} onClick={()=>state.selectHex(h.h3)}><span className="rank-number">0{i+1}</span><span className="recommendation-copy"><strong>{siteName(h.h3)}</strong><small>{h.raw.landuse} · {h.center[1].toFixed(3)}° N</small><span className="site-reason">{[...h.parts].sort((a,b)=>b.contribution-a.contribution)[0]?.label} advantage</span></span><span className="recommendation-score">{h.score100}<small>/100</small></span></button>)}{!top.length&&<div className="empty-state">No eligible sites in this area. Relax a constraint or clear the search boundary.</div>}</div>
        <button className="button full subtle" onClick={()=>{top.slice(0,3).forEach(h=>{if(!useSiteScope.getState().compare.includes(h.h3)&&useSiteScope.getState().compare.length<3)state.toggleCompare(h.h3);});setPanel("compare");}}><GitCompareArrows size={15}/>Compare top locations<ArrowUpRight size={14}/></button>
        <div className="sidebar-footer"><span className="status-dot"/> {format(data.hexes.length)} cells · H3 resolution {city.resolution}<small>All analysis layers are synthetic unless imported.</small></div>
      </aside>
      <main className="map-workspace">
        <div className="metrics-row"><div><span>Locations analyzed</span><strong>{format(filtered.length)}<small>city cells</small></strong></div><div><span>Eligible locations</span><strong>{format(eligible.length)}<small>meet your criteria</small></strong></div><div><span>Best readiness</span><strong className="green-text">{top[0]?.score100??"—"}<small>/ 100</small></strong></div><div><span>Underserved areas</span><strong>{filtered.filter(h=>h.eligible&&h.underserved).length}<small>opportunities</small></strong></div></div>
        <div className="map-toolbar"><form onSubmit={e=>{e.preventDefault();runSearch();}} className="map-search"><Search size={15}/><input aria-label="Search site or coordinates" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Site ID or latitude, longitude"/><button type="submit" aria-label="Search"><ArrowRight size={14}/></button></form><div className="map-actions"><button className={panel==="layers"?"active":""} onClick={()=>togglePanel("layers")}><Layers size={15}/>Layers <span>{layers.filter(l=>l.visible).length}</span></button><button className={drawing?"active":""} onClick={()=>{setDrawing(!drawing);setDraft([]);setPlacing(false);}}><Pentagon size={15}/>{drawing?"Cancel":"Draw area"}</button><button className={panel==="scenario"?"active":""} onClick={()=>togglePanel("scenario")}><FlaskConical size={15}/>What if?</button></div></div>
        <div className="map-stage"><ExplorerMap center={city.center} cells={before?baseline:scored} selected={selected?.h3??null} top={before?topSites(baseline,3):top.slice(0,3)} layers={layers} overlay={overlay} competitors={before?data.competitors:simulated.competitors} clusters={clusterData} bands={bands} polygon={drawing?draft:state.drawnPolygon??[]} drawing={drawing} placing={placing} uploaded={uploaded} before={before} onSelect={state.selectHex} onPoint={onMapPoint}/>
          {drawing&&<div className="area-actions"><span>{draft.length} vertices</span><button disabled={draft.length<3} onClick={()=>{state.setDrawnPolygon(draft);setDrawing(false);}}>Apply area</button><button disabled={!draft.length} onClick={()=>setDraft(d=>d.slice(0,-1))}>Undo</button></div>}
          {state.drawnPolygon&&!drawing&&<button className="clear-area" onClick={()=>state.setDrawnPolygon(null)}><X size={12}/>Clear search area · {filtered.length} cells</button>}
          {hasScenario&&<div className="scenario-switch"><FlaskConical size={14}/><span>Scenario active</span><button onClick={()=>setBefore(!before)}>{before?"Show scenario":"View baseline"}</button></div>}
        </div>
        <div className="map-bottom-bar"><span><i className="status-dot"/>Analysis updated locally</span><span>{city.name} · WGS84 · Synthetic data</span><button onClick={()=>setPanel("layers")}>Data sources <Info size={12}/></button></div>
        <div className="insight-strip"><span className="insight-icon"><Sparkles size={18}/></span><div><strong>A clearer view of your next move.</strong><p>{top[0]?`${siteName(top[0].h3)} leads with ${top[0].score100}/100. ${eligible.length} locations meet your current constraints.`:"No sites meet all current constraints. Adjust your priorities to explore alternatives."}</p></div><button onClick={()=>setPanel("scenario")} aria-label="Open scenario simulator"><ArrowUpRight size={20}/></button></div>
      </main>
      <aside className="site-detail">
        <div className="detail-heading"><span className="section-label">LOCATION INSIGHTS</span><span className="live-tag">{hasScenario?"SCENARIO":"LIVE"}</span></div>
        {selected?<><div className="site-title"><span className="location-icon"><MapPin size={19}/></span><div><h2>{siteName(selected.h3)}</h2><p>{city.name} · {selected.raw.landuse} zone</p></div></div>
          <div className="score-card"><div className="score-ring" style={{background:`conic-gradient(#38876a ${selected.score100}%, #e7ece7 0)`}}><div><strong>{selected.score100}</strong><span>OUT OF 100</span></div></div><div><span className={`suitability ${!selected.eligible?"excluded":""}`}>{!selected.eligible?"Excluded":selected.score100>=75?"Strong potential":selected.score100>=55?"Worth exploring":"Needs review"}</span><p>Site readiness score</p>{hasScenario&&baseSelected&&<span className="score-delta">{selected.score100-baseSelected.score100>=0?"+":""}{selected.score100-baseSelected.score100} pts from baseline</span>}</div></div>
          <div className="detail-tabs"><button className={detailTab==="overview"?"active":""} onClick={()=>setDetailTab("overview")}>Overview</button><button className={detailTab==="access"?"active":""} onClick={()=>{setDetailTab("access");setShowTravel(true);}}>Catchment</button><button className={detailTab==="data"?"active":""} onClick={()=>setDetailTab("data")}>Evidence</button></div>
          {detailTab==="overview"&&<><div className="breakdown-title">What shapes this score <span>CONTRIBUTION</span></div><div className="factor-breakdown">{selected.parts.map(p=><div key={p.layer}><div><span>{p.label}</span><strong>{(p.contribution*100).toFixed(1)}<small> pts</small></strong></div><div className="factor-track"><i style={{width:`${p.value*100}%`}}/></div><small>{Math.round(p.weight*100)}% weight · {Math.round(p.value*100)}/100 factor score</small></div>)}</div>
          <div className="explanation-card"><Sparkles size={15}/><strong>Why this location?</strong><p>{[...selected.parts].sort((a,b)=>b.contribution-a.contribution).slice(0,2).map(p=>p.label.toLowerCase()).join(" and ")} contribute most to this score. {selected.eligible?"It meets all active constraints.":selected.blockedBy.join("; ")+"."} {selected.underserved?"Strong demand with limited competition suggests an underserved market.":`The weakest factor is ${[...selected.parts].sort((a,b)=>a.value-b.value)[0]?.label.toLowerCase()}.`}</p><small>Calculated from the current scoring model</small></div>
          <div className="confidence-line"><span className="status-dot"/><span>{selected.robustness[0]!.toUpperCase()+selected.robustness.slice(1)} neighborhood stability</span><Info size={13}/></div><p className="fine-print">Stability reflects nearby score variation, not prediction accuracy. Synthetic inputs require field validation.</p></>}
          {detailTab==="access"&&<div className="catchment-panel"><h3>How far does this site reach?</h3><p>Travel-time coverage within the analyzed city grid.</p><div className="segmented">{(["walk","drive"] as const).map(m=><button key={m} className={mode===m?"active":""} onClick={()=>{setMode(m);setShowTravel(true);}}>{m==="walk"?"Walking":"Driving"}</button>)}</div>{bands.map(b=><div className="travel-band" key={b.minutes}><span><Route size={15}/>{b.minutes} min</span><strong>{format(b.population)}<small>estimated people</small></strong><small>{b.area.toFixed(1)} km² · {b.cells.length} cells</small></div>)}<label className="check-row"><input type="checkbox" checked={showTravel} onChange={e=>setShowTravel(e.target.checked)}/>Show catchment on map</label><p className="fine-print">{roadTravel?"OSRM road travel times. Reachable population is estimated from synthetic cell population; coverage is clipped to this grid.":"Demo network estimate: H3 neighbors, modeled travel speed and accessibility. These are not measured road isochrones. Population assumes up to 4,200 residents per cell."}</p>{mode==="drive"&&<button className="button full" disabled={routing} onClick={()=>void roadCatchment()}>{routing?"Fetching road travel times…":"Use OSRM road routing"}</button>}</div>}
          {detailTab==="data"&&<div className="evidence-panel"><h3>Source values</h3><p className="fine-print">Normalized inputs (0–1), synthetic unless replaced by an imported feature.</p>{Object.entries(selected.raw).filter(([k])=>!["boundary","center"].includes(k)).map(([k,v])=><div key={k}><span>{k}</span><b>{typeof v==="number"?v.toFixed(3):String(v)}</b></div>)}<p className="fine-print">Coordinates: {selected.center[1].toFixed(5)}, {selected.center[0].toFixed(5)}<br/>Gi* z-score: {selected.gi_z.toFixed(2)}. Exploratory significance at |z| &gt; 1.96; no multiple-testing correction.</p></div>}
          <button className={`button full ${state.compare.includes(selected.h3)?"subtle":"primary"}`} onClick={()=>addCompare(selected.h3)}>{state.compare.includes(selected.h3)?<Check size={16}/>:<Plus size={16}/>} {state.compare.includes(selected.h3)?"Added to comparison":"Add to comparison"}</button>
        </>:<div className="empty-state">Select a location on the map.</div>}
      </aside>
    </div>
    {panel&&<div className="drawer-backdrop" onClick={()=>setPanel(null)}><section className={`workspace-drawer ${panel==="compare"?"wide":""}`} role="dialog" aria-modal="true" aria-label={`${panel} panel`} onClick={e=>e.stopPropagation()}><div className="drawer-header"><div><span className="eyebrow">SITESCOPE WORKSPACE</span><h2>{{layers:"The layers behind the location",weights:"Your priorities, your score",scenario:"A small change. A different future.",compare:"Find your strongest candidate",reports:"Take your analysis with you"}[panel]}</h2></div><button className="icon-button" aria-label="Close panel" autoFocus onClick={()=>setPanel(null)}><X size={21}/></button></div><div className="drawer-body">
      {panel==="layers"&&<><p className="panel-intro">Combine spatial layers to see the story behind each location. Opacity changes the map, not the score.</p>{layers.map(l=><div className="layer-control" key={l.id}><label><input type="checkbox" checked={l.visible} onChange={e=>setLayers(ls=>ls.map(x=>x.id===l.id?{...x,visible:e.target.checked}:x))}/><i style={{background:l.color}}/><span>{l.label}</span><small>{l.id==="score"?"COMPOSITE":"DEMO"}</small></label>{l.visible&&<div className="opacity-control"><span>Opacity</span><input aria-label={`${l.label} opacity`} type="range" min="0" max="100" value={l.opacity} onChange={e=>setLayers(ls=>ls.map(x=>x.id===l.id?{...x,opacity:+e.target.value}:x))}/><span>{l.opacity}%</span></div>}</div>)}<h3>Spatial patterns</h3><select className="field" aria-label="Spatial overlay" value={overlay} onChange={e=>setOverlay(e.target.value)}><option value="none">No overlay</option><option value="hotspots">Gi* hot spots & cold spots</option><option value="underserved">Underserved opportunities</option><option value="clusters">Competitor clusters · DBSCAN</option></select><p className="fine-print">{clusterData.length} competitor clusters · DBSCAN radius 800 m, minimum 3 points. Hot spots use H3 two-ring neighborhoods.</p><h3>Add your own data</h3><p className="fine-print">GeoJSON in WGS84. Polygon properties or matching h3 IDs can replace normalized population, footfall, accessibility, complementary, rent, floodRisk, parking, or landuse inputs. Other features are map overlays.</p><input ref={uploadRef} type="file" accept=".geojson,.json" className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(f)void importLayer(f);}}/><button className="button full" onClick={()=>uploadRef.current?.click()}><Upload size={16}/>Import GeoJSON layer</button>{uploaded.map((l,i)=><label className="check-row" key={i}><input type="checkbox" checked={l.visible} onChange={e=>setUploaded(ls=>ls.map((x,j)=>i===j?{...x,visible:e.target.checked}:x))}/>{l.name}</label>)}{uploaded.length>0&&<button className="text-button" onClick={()=>{setUploaded([]);setOverrides({});setNotice("Imported overlays and scoring overrides cleared.");}}><Trash2 size={14}/>Clear all imports and restore demo data</button>}</>}
      {panel==="weights"&&<><p className="panel-intro">Every adjustment recalculates all sites. Weights are normalized automatically to a total of 100%.</p>{Object.entries(config.weights).map(([key,value])=><div className="slider-field" key={key}><label htmlFor={`weight-${key}`}>{FACTORS[key]??key}<b>{Math.round(value/Object.values(config.weights).reduce((s,v)=>s+v,0)*100)}%</b></label><input id={`weight-${key}`} type="range" min="0" max="100" value={Math.round(value/(Math.max(...Object.values(config.weights))<=1?1:100)*100)} onChange={e=>{const scale=Math.max(...Object.values(config.weights))<=1?1:100;const v=+e.target.value/100*scale;if(v===0&&Object.entries(config.weights).every(([k,w])=>k===key||w===0))return;state.setWeight(key as LayerId,v);}}/></div>)}<div className="two-fields"><label>Competition<select className="field" value={config.competitionMode} onChange={e=>state.patchConfig({competitionMode:e.target.value as typeof config.competitionMode})}><option value="avoid">Avoid competitors</option><option value="neutral">Neutral</option><option value="cluster">Prefer clusters</option></select></label><label>Search radius<select className="field" value={config.competitionRadius} onChange={e=>state.patchConfig({competitionRadius:+e.target.value})}>{[500,800,1000,2000,3000,5000,10000].map(n=><option key={n} value={n}>{n/1000} km</option>)}</select></label></div><label className="slider-field">Distance decay · {(config.decayD0/1000).toFixed(1)} km<input aria-label="Distance decay" type="range" min="200" max="8000" step="100" value={config.decayD0} onChange={e=>state.patchConfig({decayD0:+e.target.value})}/></label><h3>Non-negotiables</h3>{Object.entries(CONSTRAINT_LABELS).map(([id,label])=><label className="check-row" key={id}><input type="checkbox" checked={config.constraints.includes(id)} onChange={e=>state.patchConfig({constraints:e.target.checked?[...config.constraints,id]:config.constraints.filter(x=>x!==id)})}/>{label}</label>)}<button className="button full" onClick={state.resetToMyAnswers}><RotateCcw size={15}/>Restore questionnaire settings</button></>}
      {panel==="scenario"&&<><p className="panel-intro">Stress-test your choice. Change demand, place a competitor, or disrupt access and watch the rankings respond.</p><div className="scenario-card"><span className="eyebrow">01 / MARKET CHANGE</span><div className="slider-field"><label htmlFor="growth">Population growth <b>{scenario.growth>0?"+":""}{scenario.growth}%</b></label><input id="growth" type="range" min="-40" max="50" value={scenario.growth} onChange={e=>setScenario(s=>({...s,growth:+e.target.value}))}/></div><p className="fine-print">Changes population across the city, capped at the normalized maximum.</p></div><div className="scenario-card"><span className="eyebrow">02 / A NEW NEIGHBOR</span><h3>What if a competitor opens nearby?</h3><p>Place a new competitor at any point on the map.</p><button className="button full" onClick={()=>{setPlacing(true);setDrawing(false);setPanel(null);setBefore(false);}}><Plus size={16}/>Place competitor on map</button>{scenario.competitors.length>0&&<p>{scenario.competitors.length} simulated competitor{scenario.competitors.length>1?"s":""} added <button className="text-button" onClick={()=>setScenario(s=>({...s,competitors:[]}))}>Clear</button></p>}</div><div className="scenario-card"><span className="eyebrow">03 / LOCAL DISRUPTION</span><p>Affects the selected site and fades over 1.5 km. Anchor: {scenario.anchor?`${scenario.anchor[1].toFixed(3)}, ${scenario.anchor[0].toFixed(3)}`:"current selection"}.</p><div className="slider-field"><label htmlFor="access-loss">Access reduction <b>{scenario.accessLoss} pts</b></label><input id="access-loss" type="range" min="0" max="80" value={scenario.accessLoss} onChange={e=>setScenario(s=>({...s,accessLoss:+e.target.value,anchor:s.anchor??selected?.center??city.center}))}/></div><div className="slider-field"><label htmlFor="flood-rise">Flood risk increase <b>{scenario.flood} pts</b></label><input id="flood-rise" type="range" min="0" max="70" value={scenario.flood} onChange={e=>setScenario(s=>({...s,flood:+e.target.value,anchor:s.anchor??selected?.center??city.center}))}/></div></div>{selected&&baseSelected&&<div className="scenario-result"><span>{siteName(selected.h3)} · BEFORE → AFTER</span><div><strong>{baseSelected.score100}</strong><ArrowRight/><strong>{selected.score100}</strong></div><p>Rank {baseRanks.get(selected.h3)??"excluded"} → {newRanks.get(selected.h3)??"excluded"} · {selected.eligible?"Eligible":selected.blockedBy.join(", ")}</p></div>}<button className="button full" onClick={()=>{setScenario(EMPTY_SCENARIO);setBefore(false);setPlacing(false);}}><RotateCcw size={15}/>Reset scenario</button></>}
      {panel==="compare"&&<>{candidates.length?<><p className="panel-intro">Compare up to three sites using the same business profile and active scenario.</p><div className="comparison-cards">{candidates.map((h,i)=><div key={h.h3}><button aria-label={`Remove ${siteName(h.h3)}`} onClick={()=>state.toggleCompare(h.h3)}><X size={14}/></button><span>0{i+1} · {siteName(h.h3)}</span><strong>{h.score100}<small>/100</small></strong><p>{h.eligible?"Eligible":"Excluded"}</p></div>)}</div><div className="radar-wrap"><ResponsiveContainer width="100%" height="100%"><RadarChart data={["demand","accessibility","competition","complementary","landuse","risk"].map(key=>({factor:FACTORS[key],...Object.fromEntries(candidates.map((h,i)=>[`site${i}`,h.subscores[key]]))}))}><PolarGrid stroke="#dce5df"/><PolarAngleAxis dataKey="factor" tick={{fill:"#687970",fontSize:11}}/><PolarRadiusAxis domain={[0,100]} tick={false} axisLine={false}/>{candidates.map((h,i)=><Radar key={h.h3} name={siteName(h.h3)} dataKey={`site${i}`} stroke={["#398569","#cd9870","#8396be"][i]} fill={["#398569","#cd9870","#8396be"][i]} fillOpacity={0.12}/>)}</RadarChart></ResponsiveContainer></div><table className="comparison-table"><thead><tr><th>Factor</th>{candidates.map((h,i)=><th key={h.h3}>Site {i+1}</th>)}</tr></thead><tbody>{candidates[0]!.parts.map(p=><tr key={p.layer}><td>{p.label}</td>{candidates.map(h=><td key={h.h3}>{Math.round((h.parts.find(x=>x.layer===p.layer)?.value??0)*100)}</td>)}</tr>)}</tbody></table><div className="explanation-card"><Sparkles size={16}/><strong>Model recommendation</strong><p>{topSites(candidates,1)[0]?`${siteName(topSites(candidates,1)[0]!.h3)} has the highest eligible readiness score among these candidates. Compare its weakest factors before making a final decision.`:"All compared sites violate an active constraint. None is recommended under this configuration."}</p></div></>:<div className="empty-state"><GitCompareArrows size={36}/><h3>A little perspective helps.</h3><p>Add locations from the insights panel, or start with the top three.</p><button className="button primary" onClick={()=>top.slice(0,3).forEach(h=>state.toggleCompare(h.h3))}>Add top three sites</button></div>}</>}
      {panel==="reports"&&<><p className="panel-intro">Export the current city, priorities and scenario results. Every report identifies demo data and excluded locations.</p><button className="export-option" onClick={()=>exportCSV(filtered,city.name)}><Download/><span><strong>Complete score data</strong><small>CSV · {filtered.length} sites, factor scores and exclusion reasons</small></span><ArrowUpRight size={18}/></button><button className="export-option" onClick={report}><FileText/><span><strong>Executive report</strong><small>Print-ready report · save as PDF from your browser</small></span><ArrowUpRight size={18}/></button><button className="export-option" onClick={()=>{const payload={city:city.id,business,config,scenario,polygon:state.drawnPolygon,selected:state.selectedH3,comparison:state.compare,generatedAt:new Date().toISOString(),dataSource:"Synthetic demo with optional local imports"};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`sitescope-${city.id}-scenario.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}><FlaskConical/><span><strong>Scenario snapshot</strong><small>JSON · configuration, scenario and selected sites</small></span><ArrowUpRight size={18}/></button><div className="explanation-card"><Info size={15}/><strong>About this dataset</strong><p>Geography uses real H3 cells in {city.name}. Population, amenities, competitors, zoning and environmental risk are generated demo values. Imported attributes override those values. Base map tiles come from OpenStreetMap / CARTO or Esri.</p></div></>}
    </div><div className="drawer-footer"><span><span className="status-dot"/>Changes apply immediately</span><button className="button primary small" onClick={()=>setPanel(null)}>Back to map <ArrowRight size={14}/></button></div></section></div>}
    {notice&&<div role="status" className="scope-toast"><Info size={16}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice("")}><X size={15}/></button></div>}
  </div>;
}
